# Page settings
baseurl = "https://rootcluster.github.io"
title = "RootCluster"
languageCode = "en-us"
theme = "elate"

[params]

  # Meta
  author = "Jerry xu"
  description = "Life's a struggle!"
  email = "incoder.xu@gmail.com"

  # Navigation
  [params.navigation]
    brand = "RootCluster"
    home = "Home"
    work = "Project"
    testimonials = "Friends"
    services = "Prospect"
    about = "About"
    contact = "Contact"

  # Hero section
  [params.hero]
    title = "Do something myself love."
    subtitle = '<a href="https://github.com/RootCluster" target="_blank">RootCluster</a> organization is learning and practice cluster, popular developer language, hot open framework, powerful algorithm...'
 
  # Intro section
  # Available icons: https://simplelineicons.github.io
  [params.intro]

  [[params.intro.item]]
    title = "Interest"
    description = "Hold their most interested in things, unit, learn step by step"
    url = "#"
    # button = "Coming Soon"
    icon = "icon-directions"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Study & Practice"
    description = "Much effort , much prosperity."
    url = "#"
    # button = "Coming Soon"
    icon = "icon-chemistry"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Graduation"
    description = "Success is inevitable if we grasp interest and practice hard."
    url = "#"
    # button = "Coming Soon"
    icon = "icon-rocket"
    img = "img_10.jpg"

  [params.intro.video]
    enable = true
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"

  # Work section
  [params.work]
    enable = true
    title = "Project"
    description = 'The purpose of work is to accumulate self and promote growth, so as to achieve a "sustainable leap" in the future.'
    footertext = 'Working makes a man poor'

    [[params.work.row]]
      # img = "https://spring.io/images/diagram-microservices-dark-4a2e5817aac093437f4f3b3a5be8be88.svg"
      img = "https://spring.io/images/diagram-microservices-88e01c7d34c688cb49556435c130d352.svg"
      alt = "microservices-spring"
      url = "https://github.com/RootCluster/rc-microservices-spring"
      title = "rc-microservices-spring"
      subtitle = "Spring official"

    [[params.work.row]]
      img = "https://spring.io/images/diagram-microservices-dark-4a2e5817aac093437f4f3b3a5be8be88.svg"
      alt = "microservices-alibaba"
      url = "https://github.com/RootCluster/rc-microservices-alibaba"
      title = "rc-microservices-alibaba"
      subtitle = "Alibaba official"

    [[params.work.row]]
      # img = "https://netty.io/images/components.png"
      img = "https://spring.io/images/diagram-microservices-dark-4a2e5817aac093437f4f3b3a5be8be88.svg"
      alt = "cluster-netty"
      url = "https://github.com/RootCluster/rc-cluster-netty"
      title = "rc-cluster-netty"
      subtitle = "Learning"

    [[params.work.row]]
      # img = "https://raw.githubusercontent.com/apache/rocketmq/master/docs/cn/image/rocketmq_design_1.png"
      img = "https://spring.io/images/diagram-microservices-dark-4a2e5817aac093437f4f3b3a5be8be88.svg"
      alt = "cluster-mq"
      url = "https://github.com/RootCluster/rc-cluster-mq"
      title = "rc-cluster-mq"
      subtitle = "Learning"

    [[params.work.row]]
      # img = "https://res.cloudinary.com/incoder/image/upload/v1614446174/rootcluster/kotlin-featured.svg"
      img = "https://spring.io/images/diagram-microservices-dark-4a2e5817aac093437f4f3b3a5be8be88.svg"
      alt = "cluster-kotlin"
      url = "https://github.com/RootCluster/rc-cluster-kotlin"
      title = "rc-cluster-kotlin"
      subtitle = "Practice"

    [[params.work.row]]
      # img = "https://spring.io/images/diagram-microservices-dark-4a2e5817aac093437f4f3b3a5be8be88.svg"
      img = "https://cdn.flowable.com/wp-content/uploads/2019/01/22093528/Flowable_Case_Management_Graphic.svg"
      alt = "cluster-flowable"
      url = "https://github.com/RootCluster/rc-cluster-flowable"
      title = "rc-cluster-flowable"
      subtitle = "Practice"

    [[params.work.row]]
      # img = "https://flutter.dev/images/arch-overview/archdiagram.png"
      img = "https://spring.io/images/diagram-microservices-dark-4a2e5817aac093437f4f3b3a5be8be88.svg"
      alt = "flutter_learn"
      url = "https://github.com/RootCluster/flutter_learn"
      title = "flutter_learn"
      subtitle = "Practice "

    [[params.work.row]]
      img = "https://www.python.org/static/community_logos/python-logo-inkscape.svg"
      # img = "https://spring.io/images/diagram-microservices-dark-4a2e5817aac093437f4f3b3a5be8be88.svg"
      alt = "cluster-python"
      url = "https://github.com/RootCluster/rc-cluster-python"
      title = "rc-cluster-python"
      subtitle = "Practice "

    [[params.work.row]]
      img = "https://rootcluster.github.io/favicon.ico"
      # img = "https://spring.io/images/diagram-microservices-dark-4a2e5817aac093437f4f3b3a5be8be88.svg"
      alt = "RootCluster"
      url = "https://github.com/RootCluster"
      title = "RootCluster Organization Other Project"
      subtitle = "etc..."

  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Friends"
    description = "If three walk together, one of them can teach me sth."

    [[params.testimonials.item]]
      quote = 'Talk is cheap, show me the code ~'
      person = 'Alyenc Chen'
      website = 'https://kaifa.dev'
      github = 'https://github.com/alyenc'
      img = "https://avatars.githubusercontent.com/u/20921136"
      alt = "alyenc"

    [[params.testimonials.item]]
      quote = "&ldquo;That's organization give be surprised, in the Fast-paced world, RootCluster make a pure technical atmosphere ,that's Rare! in the future, I will be with <a href='https://www.twodragonlake.com' target='_blank'>TwoDragonLake</a> join open source of the rootcluster organization as a full stack developer.some work that including but not limited to: security、distributed computing、algorithm、system design、iot、big data etc... i believe, In the near future we come with partner together will be the best developer of HangZhou. let`s do it! wola!~.&rdquo;"
      person = 'Ceaser Wang'
      website = 'https://ceaser.wang'
      github = 'https://github.com/1156721874'
      img = "https://avatars.githubusercontent.com/u/9300978"
      alt = "ceaser"

    [[params.testimonials.item]]
      quote = "&ldquo;Lazy people make the world. &rdquo;"
      person = 'Killua Wang'
      website = 'https://blog.dazhidayong.cn'
      github = 'https://github.com/Killua67'
      img = "https://avatars.githubusercontent.com/u/20350703"
      alt = "killua"

  # Services section
  [params.services]
    enable = true
    title = "Prospect"
    description = "TO BE OR NOT TO BE"

    [[params.services.item]]
      title = "Summary"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-layers2"
    [[params.services.item]]
      title = "CMS &amp; eCommerce"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"      
      icon = "icon-trophy"
    [[params.services.item]]
      title = "Deliberate Practice"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"      
      icon = "icon-note"
    [[params.services.item]]
      title = "CMS &amp; eCommerce"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"      
      icon = "icon-diamond"

  # About section
  [params.about]
    enable = false
    title = "About"
    description = "You can contact me, if you have any ideas or need to talk to me, etc."

    [[params.about.item]]
      name = "Jerry xu"
      position = "Java Developer"
      description = "Life's a struggle ~"
      img = "https://avatars3.githubusercontent.com/u/12027865?s=460&v=4"
      alt = "Jerry"
      social = [
        ["icon-twitter", "https://twitter.com/_incoder"],
        ["icon-weibo", "http://weibo.com/onblade"],
        ["icon-github", "https://github.com/BladeCode"]
      ]    

  # Counters section
  [params.counters]
    enable = true
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Ongoing projects"
      icon = "icon-briefcase"
      from = 0
      to = 7
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Contribution Organizations"
      icon = "icon-people"
      from = 0
      to = 2
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = false
    form = false
    title = "Get in touch"
    description = "If you have any questions or would like to communicate with me, please contact me"
    
    # Available icons: https://simplelineicons.github.io
    details = [
        ["icon-home", "HangZhou · China"],
        ["icon-qq", "605604615"],
        ["icon-envelope", "<a href='mailto:incoder.xu@gmail.com'>incoder.xu@gmail.com</a>"],
        ["icon-globe", '<a href="https://incoder.org" target="_blank">BladeCode</a>']
      ]


  # Footer section
  [params.footer]
    enable = true
    copyright = '© 2018 - 2021. RootCluster All Rights Reserved. <br>Created by <a href="https://gohugo.io" target="_blank">Hugo</a> Theme for <a href="https://themes.gohugo.io/hugo-elate-theme" target="_blank">Elate</a>'
    links = [
        ["icon-twitter", "https://twitter.com/_incoder"],
        ["icon-weibo", "https://weibo.com/onblade"],
        ["icon-github", "https://www.github.com/BladeCode"]
      ]